name: game
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  font_awesome_flutter: ^10.6.0
  gesture_x_detector: ^1.1.1
  get: ^4.6.6
  ilp_file_codec:
    path: ../ilp_file_codec
  i18n:
    path: ../i18n
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  synchronized: ^3.1.0+1
  universal_io: ^2.2.2
  url_launcher: ^6.2.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/ilp/
