name: game
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^5.0.0
  confetti: ^0.7.0
  dio: ^5.3.0
  dio_cache_interceptor: ^3.4.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  gesture_x_detector: ^1.1.1
  get: ^4.6.5
  ilp_file_codec:
    path: ../ilp_file_codec
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  synchronized: ^3.1.0
  universal_io: ^2.2.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/ilp/
