name: mobile
description: Find Up!
publish_to: 'none'

version: 1.0.5+10

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ilp_file_codec:
    path: ../../package/ilp_file_codec
  game:
    path: ../../package/game

  get: ^4.6.5
  oktoast: ^3.3.1
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter
  image_gallery_saver: ^2.0.3
  firebase_core: ^2.15.1
  dynamic_color: ^1.6.6
  change_app_package_name: ^1.1.0
  url_launcher: ^6.1.14
  package_info_plus: ^4.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter_launcher_icons:
  android: "ic_launcher"
#  ios: true
  image_path: "icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:

  uses-material-design: true

  assets:
    - assets/