name: mobile
description: Find Up!
publish_to: 'none'

version: 1.1.0+18

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ilp_file_codec:
    path: ../../package/ilp_file_codec
  game:
    path: ../../package/game
  i18n:
    path: ../../package/i18n
  ilp_assets:
    path: ../../package/ilp_assets

  get: ^4.6.6
  oktoast: ^3.4.0
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter
  image_gallery_saver: ^2.0.3
  firebase_core: ^2.24.2
  dynamic_color: ^1.6.9
  change_app_package_name: ^1.1.0
  url_launcher: ^6.2.4
  package_info_plus: ^5.0.1
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.4.1
  flutter_staggered_grid_view: ^0.7.0
  unity_ads_plugin: ^0.3.11
  google_fonts: ^6.2.1
  yaml_edit: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  #  ios: true
  image_path: "logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true