name: windows
description: Find Up!
publish_to: 'none'

version: 1.3.11

environment:
  sdk: '>=3.0.5 <4.0.0'

msix_config:
  display_name: Find Up!
  publisher_display_name: gzlock
  identity_name: 49786gzlock.18476445307EC
  publisher: CN=823366A9-ECB6-42AB-BC60-76E199592B6F
  store: true
  msix_version: 1.3.11.0
  logo_path: icon.png
  capabilities: internetClient
  languages: zh-cn, en-us
  file_extension: .ilp
  windows_build_args: --target=./lib/main_microsoft_store.dart
  show_prompt: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ui:
    path: ../../package/ui
  ilp_file_codec:
    path: ../../package/ilp_file_codec
  game:
    path: ../../package/game
  ilp_assets:
    path: ../../package/ilp_assets

  get: ^4.6.6
  intl: any
  window_manager: ^0.3.8
  oktoast: ^3.4.0
  file_selector: ^1.0.3
  shared_preferences: ^2.2.3
  path: ^1.9.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  touchable: ^1.0.2
  confetti: ^0.7.0
  desktop_drop: ^0.4.4
  dynamic_color: ^1.7.0
  windows_single_instance: ^1.0.1
  msix: ^3.16.7
  chinese_font_library: ^1.1.0
  package_info_plus: ^7.0.0
  steamworks: 0.4.6
  ffi: ^2.1.2
  flutter_svg: ^2.0.10+1
  dotted_line: ^3.2.2
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  dynamic_parallel_queue: ^1.0.3+2
  tweener: ^2.2.3
  path_drawing: ^1.0.1
  borders: 0.3.0
  yaml_edit: ^2.2.0
  enough_convert: ^1.6.0
  hotkey_manager: ^0.2.2
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  #  android: "launcher_icon"
  #  ios: true
  image_path: "icon.png"
  #  web:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"
  windows:
    generate: true
    #    image_path: "path/to/image.png"
    icon_size: 256 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/