name: windows
description: Find Up!.
publish_to: 'none'

version: 1.0.7

environment:
  sdk: '>=3.0.5 <4.0.0'

msix_config:
  display_name: Find Up!
  publisher_display_name: gzlock
  identity_name: 49786gzlock.18476445307EC
  publisher: CN=823366A9-ECB6-42AB-BC60-76E199592B6F
  store: true
  msix_version: 1.0.7.0
  logo_path: icon.png
  capabilities: internetClient
  languages: zh-cn, en-us
  file_extension: .ilp
  windows_build_args: --target=./lib/main_prod.dart
  show_prompt: true

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: any
  window_manager: ^0.3.6
  ilp_file_codec:
    path: ../../package/ilp_file_codec
  game:
    path: ../../package/game
  oktoast: ^3.3.1
  file_selector: ^1.0.1
  shared_preferences: ^2.2.1
  path: ^1.8.3
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  image: ^4.0.17
  touchable: ^1.0.2
  flutter_localizations:
    sdk: flutter
  confetti: ^0.7.0
  desktop_drop: ^0.4.3
  dynamic_color: ^1.6.6
  windows_single_instance: ^1.0.0
  msix: ^3.16.1
  chinese_font_library: ^1.0.2
  package_info_plus: ^4.1.0
  steamworks: ^0.4.4
  ffi: ^2.1.0
  flutter_svg: ^2.0.7
  dotted_line: ^3.2.2
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
  image_path: "icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
  windows:
    generate: true
#    image_path: "path/to/image.png"
    icon_size: 256 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/